from database import SessionLocal, engine, Base
from models import Car

# Ensure tables exist
Base.metadata.create_all(bind=engine)

CARS = [
    # ── Hatchbacks ────────────────────────────────────────────────────
    {
        "make": "Maruti Suzuki",
        "model": "Swift",
        "variant": "ZXi+ AMT",
        "price_lakh": 8.70,
        "fuel_type": "Petrol",
        "transmission": "AMT",
        "seating": 5,
        "mileage": 22.56,
        "safety_rating": 3.0,
        "body_type": "Hatchback",
        "pros": "Best-in-class fuel efficiency, Strong resale value",
        "cons": "Rear seat space is tight, Basic safety in lower trims",
    },
    {
        "make": "Hyundai",
        "model": "i20",
        "variant": "Asta(O) 1.0 Turbo DCT",
        "price_lakh": 11.30,
        "fuel_type": "Petrol",
        "transmission": "DCT",
        "seating": 5,
        "mileage": 20.25,
        "safety_rating": 3.0,
        "body_type": "Hatchback",
        "pros": "Premium interiors with segment-best features, Peppy turbo engine",
        "cons": "Expensive for a hatchback, DCT can feel jerky in traffic",
    },
    {
        "make": "Tata",
        "model": "Altroz",
        "variant": "XZ+ Dark Edition",
        "price_lakh": 9.50,
        "fuel_type": "Petrol",
        "transmission": "Manual",
        "seating": 5,
        "mileage": 18.00,
        "safety_rating": 5.0,
        "body_type": "Hatchback",
        "pros": "5-star GNCAP safety rating, Solid build quality",
        "cons": "No automatic option in petrol, Engine feels underpowered on highways",
    },
    {
        "make": "Maruti Suzuki",
        "model": "Baleno",
        "variant": "Alpha AMT",
        "price_lakh": 9.80,
        "fuel_type": "Petrol",
        "transmission": "AMT",
        "seating": 5,
        "mileage": 22.35,
        "safety_rating": 3.0,
        "body_type": "Hatchback",
        "pros": "Spacious cabin for a hatchback, Excellent fuel economy",
        "cons": "AMT gearbox is sluggish, Average build quality",
    },
    # ── Sedans ────────────────────────────────────────────────────────
    {
        "make": "Honda",
        "model": "City",
        "variant": "ZX CVT",
        "price_lakh": 14.70,
        "fuel_type": "Petrol",
        "transmission": "CVT",
        "seating": 5,
        "mileage": 18.40,
        "safety_rating": 4.0,
        "body_type": "Sedan",
        "pros": "Refined engine with excellent ride quality, Spacious rear seat and big boot",
        "cons": "Pricing is on the higher side, Misses out on sunroof in base variants",
    },
    {
        "make": "Hyundai",
        "model": "Verna",
        "variant": "SX(O) 1.5 Turbo DCT",
        "price_lakh": 17.40,
        "fuel_type": "Petrol",
        "transmission": "DCT",
        "seating": 5,
        "mileage": 17.80,
        "safety_rating": 5.0,
        "body_type": "Sedan",
        "pros": "Feature-loaded with ADAS and ventilated seats, Powerful 160hp turbo engine",
        "cons": "Turbo variant is expensive, Firm ride quality on bad roads",
    },
    {
        "make": "Maruti Suzuki",
        "model": "Ciaz",
        "variant": "Alpha AT",
        "price_lakh": 11.80,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seating": 5,
        "mileage": 20.04,
        "safety_rating": 3.0,
        "body_type": "Sedan",
        "pros": "Class-leading boot space and fuel efficiency, Comfortable ride for long drives",
        "cons": "Dated interior design, Lacks modern connected-car features",
    },
    {
        "make": "Skoda",
        "model": "Slavia",
        "variant": "Style 1.5 TSI DSG",
        "price_lakh": 18.70,
        "fuel_type": "Petrol",
        "transmission": "DSG",
        "seating": 5,
        "mileage": 18.72,
        "safety_rating": 4.0,
        "body_type": "Sedan",
        "pros": "Engaging driving dynamics and handling, Punchy 150hp TSI engine",
        "cons": "After-sales service network is limited, Rear AC vents missing in some variants",
    },
    # ── Compact SUVs ──────────────────────────────────────────────────
    {
        "make": "Hyundai",
        "model": "Creta",
        "variant": "SX(O) 1.5 Turbo DCT",
        "price_lakh": 20.15,
        "fuel_type": "Petrol",
        "transmission": "DCT",
        "seating": 5,
        "mileage": 17.00,
        "safety_rating": 5.0,
        "body_type": "SUV",
        "pros": "Segment leader with premium features and ADAS, Smooth turbo-DCT powertrain",
        "cons": "Top variants are priced like mid-size SUVs, Average ground clearance for an SUV",
    },
    {
        "make": "Tata",
        "model": "Nexon",
        "variant": "XZA+ (O) Diesel AT",
        "price_lakh": 15.50,
        "fuel_type": "Diesel",
        "transmission": "AMT",
        "seating": 5,
        "mileage": 23.22,
        "safety_rating": 5.0,
        "body_type": "SUV",
        "pros": "5-star safety and solid build, Good diesel engine with great mileage",
        "cons": "AMT gearbox is not the smoothest, Boot space is below average",
    },
    {
        "make": "Kia",
        "model": "Seltos",
        "variant": "HTX+ 1.5 Turbo DCT",
        "price_lakh": 19.00,
        "fuel_type": "Petrol",
        "transmission": "DCT",
        "seating": 5,
        "mileage": 16.50,
        "safety_rating": 5.0,
        "body_type": "SUV",
        "pros": "Feature-rich with panoramic sunroof and Bose audio, Sharp design with strong road presence",
        "cons": "Turbo DCT can overheat in stop-and-go traffic, No diesel automatic option",
    },
    {
        "make": "Maruti Suzuki",
        "model": "Grand Vitara",
        "variant": "Alpha+ Strong Hybrid",
        "price_lakh": 19.65,
        "fuel_type": "Hybrid",
        "transmission": "eCVT",
        "seating": 5,
        "mileage": 27.97,
        "safety_rating": 5.0,
        "body_type": "SUV",
        "pros": "Outstanding real-world fuel efficiency with hybrid, 5-star safety rating",
        "cons": "Strong hybrid is FWD only — no AWD, Cabin could feel more premium at this price",
    },
    # ── Mid-size & Full-size SUVs ─────────────────────────────────────
    {
        "make": "Mahindra",
        "model": "XUV700",
        "variant": "AX7 L Diesel AT",
        "price_lakh": 24.50,
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "seating": 7,
        "mileage": 16.00,
        "safety_rating": 5.0,
        "body_type": "SUV",
        "pros": "Massive feature list with ADAS at an aggressive price, Powerful 185hp diesel engine",
        "cons": "Long waiting periods, Third row is cramped for adults",
    },
    {
        "make": "Mahindra",
        "model": "Thar",
        "variant": "LX Diesel AT 4WD",
        "price_lakh": 17.50,
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "seating": 4,
        "mileage": 15.20,
        "safety_rating": 4.0,
        "body_type": "SUV",
        "pros": "Iconic off-road capability with true 4x4, Head-turning lifestyle design",
        "cons": "Poor ride comfort on highways, Limited practicality as a daily driver",
    },
    {
        "make": "Tata",
        "model": "Harrier",
        "variant": "Fearless+ AT",
        "price_lakh": 24.00,
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "seating": 5,
        "mileage": 14.60,
        "safety_rating": 5.0,
        "body_type": "SUV",
        "pros": "Stunning road presence based on Land Rover platform, 5-star safety with comprehensive ADAS",
        "cons": "No petrol engine option, Infotainment can be laggy at times",
    },
    # ── MPVs ──────────────────────────────────────────────────────────
    {
        "make": "Maruti Suzuki",
        "model": "Ertiga",
        "variant": "ZXi+ AT",
        "price_lakh": 12.80,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "seating": 7,
        "mileage": 20.51,
        "safety_rating": 3.0,
        "body_type": "MPV",
        "pros": "Best value-for-money 7-seater, Light steering makes city driving easy",
        "cons": "Third row only for kids, Feels underpowered when fully loaded",
    },
    {
        "make": "Kia",
        "model": "Carens",
        "variant": "Luxury Plus 1.5 Turbo DCT",
        "price_lakh": 16.50,
        "fuel_type": "Petrol",
        "transmission": "DCT",
        "seating": 7,
        "mileage": 16.00,
        "safety_rating": 3.0,
        "body_type": "MPV",
        "pros": "Spacious cabin with ventilated seats for a 3-row car, Punchy turbo engine with smooth DCT",
        "cons": "3-star safety rating is disappointing, Third row legroom is tight for tall passengers",
    },
    # ── EVs ───────────────────────────────────────────────────────────
    {
        "make": "Tata",
        "model": "Nexon EV",
        "variant": "Empowered+ LR",
        "price_lakh": 17.50,
        "fuel_type": "Electric",
        "transmission": "Automatic",
        "seating": 5,
        "mileage": 325.0,  # km range
        "safety_rating": 5.0,
        "body_type": "SUV",
        "pros": "Most affordable long-range EV in India, 5-star safety and solid build quality",
        "cons": "Fast-charging infra is still sparse outside metros, Boot space reduced due to battery",
    },
    {
        "make": "MG",
        "model": "ZS EV",
        "variant": "Exclusive Pro",
        "price_lakh": 24.00,
        "fuel_type": "Electric",
        "transmission": "Automatic",
        "seating": 5,
        "mileage": 461.0,  # km range
        "safety_rating": 5.0,
        "body_type": "SUV",
        "pros": "Excellent 461km range with fast-charging support, Spacious cabin with panoramic sunroof",
        "cons": "Limited MG service network in smaller cities, Pricey compared to IC-engine SUVs",
    },
    {
        "make": "Hyundai",
        "model": "Ioniq 5",
        "variant": "Long Range AWD",
        "price_lakh": 46.00,
        "fuel_type": "Electric",
        "transmission": "Automatic",
        "seating": 5,
        "mileage": 631.0,  # km range
        "safety_rating": 5.0,
        "body_type": "SUV",
        "pros": "Ultra-fast 800V charging and futuristic design, Premium lounge-like interior with reclining seats",
        "cons": "Very expensive with limited mass-market appeal, Ground clearance is low for Indian roads",
    },
]


def seed():
    db = SessionLocal()
    try:
        # Clear existing cars
        db.query(Car).delete()
        db.commit()

        for car_data in CARS:
            db.add(Car(**car_data))

        db.commit()
        print(f"Seeded {len(CARS)} cars")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
